title: Lehui Chen's Homepage
page-top-title: Lehui Chen
top-section-bg-text: Guangdong University of Technology
home-subtitle: Lehui Chen&ensp;|&ensp;陈乐辉
copyright-text: '&copy; This website is dedicated to my university life. Lehui Chen. All Rights Reserved.'
